# Generated by Django 4.0 on 2021-12-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
